In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'YOUR_AUTH_TOKEN_HERE' # change this auth token

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:6 https://cli.github.com/packages stable InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,855 kB]
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,161 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,594 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,520 kB]
Get:16 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [83.2 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,822 kB]
Get:18 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,411 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,289 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [5,963 kB]
Fetched 35.1 MB in 12s (2,974 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.21).
gnupg is already the newest version (2.2.27-3ubuntu2.4).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [12.9 kB]
Fetched 25.1 kB in 1s (19.5 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 32.0 MB of archives.
After this operation, 197 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.19.5-1nodesource1 [32.0 MB]
Fetched 32.0 MB in 0s (66.4 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 125080 files and directories currently installed.)
Preparing to unpack .../nodejs_20.19.5-1nodesource1_amd64.deb ...
Unpacking nodejs (20.19.5-1nodesource1) ...
Setting up nodejs (20.19.5-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.19.5

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-01.csv" -s "tiktok shop since:2025-10-01 until:2025-10-02 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-01 until:2025-10-02 lang:id

 (4)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-01.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-01.csv
Total tweets saved: 39

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-01.csv
Total tweets saved: 57

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 57 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-01.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1973517795410551195,Wed Oct 01 22:38:03 +0000 2025,1,Buku Putih Tiktok Affiliate https://t.co/eGeV2...,1973517795410551195,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197351779541055...,1584003824687071236,NaN
1,1973447989403521300,Wed Oct 01 18:01:06 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1973448100351189434,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197344810035118...,1198334086588186624,NaN
2,1973447338879541718,Wed Oct 01 17:58:32 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1973447451844681789,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197344745184468...,1198334086588186624,NaN
3,1973443899571200244,Wed Oct 01 17:45:05 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1973444067959906674,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197344406795990...,1198334086588186624,NaN
4,1973437942892024246,Wed Oct 01 17:20:44 +0000 2025,1,me rendi ao tiktok shop,1973437942892024246,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197343794289202...,881170322761928704,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1fuzY-TFZGs2Qd5Uhjm1MsZzLz2GVjoycqqjzQt16jgQ/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-02.csv" -s "tiktok shop since:2025-10-02 until:2025-10-03 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-02 until:2025-10-03 lang:id

 (4) (5) (6)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-02.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-02.csv
Total tweets saved: 38

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-02.csv
Total tweets saved: 53

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-02.csv
Total tweets saved: 70

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 70 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-02.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1973739224647311748,Thu Oct 02 13:17:56 +0000 2025,0,pacarku tetiba nyanyi lagu tiktok shop,1973739224647311748,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197373922464731...,1882689256130580480,NaN
1,1973738251476455797,Thu Oct 02 13:14:04 +0000 2025,0,Jam tangan mewah harga receh beli disini Shope...,1973738251476455797,https://pbs.twimg.com/ext_tw_video_thumb/19737...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197373825147645...,495631121,NaN
2,1973658852026712305,Thu Oct 02 13:11:32 +0000 2025,0,@1shineonstage Bnr bgt tiktok shop suka lambat...,1973737614063853965,NaN,1shineonstage,in,NaN,0,1,0,https://x.com/undefined/status/197373761406385...,1540664861117796353,NaN
3,1973730197733282013,Thu Oct 02 12:42:04 +0000 2025,11,disclaimer: honest review berdasarkan pemakaia...,1973730200841330835,NaN,_matchagalu,in,NaN,0,1,0,https://x.com/undefined/status/197373020084133...,1915302007050821637,NaN
4,1973718428050751523,Thu Oct 02 12:32:33 +0000 2025,0,@myeongminming Soalnya ngerayunya kayak koko2 ...,1973727803595235798,https://pbs.twimg.com/media/G2QW-hia4AASj47.jpg,myeongminming,in,NaN,0,0,0,https://x.com/undefined/status/197372780359523...,1952732890628075520,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/19JLvHShXJ9q3qpNQDmcP7_F-nQge_Se6vvc94BHNaw8/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-03.csv" -s "tiktok shop since:2025-10-03 until:2025-10-04 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-03 until:2025-10-04 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-03.csv
Total tweets saved: 20

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-03.csv
Total tweets saved: 39

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-03.csv
Total tweets saved: 59

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-03.csv
Total tweets saved: 78

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 78 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-03.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1974263036601848090,Fri Oct 03 23:59:22 +0000 2025,0,#s wts pc iu dom sby bs co via tokped/tiktok s...,1974263036601848090,https://pbs.twimg.com/media/G2X9xJnasAAcHHJ.jpg,NaN,in,NaN,0,0,4,https://x.com/undefined/status/197426303660184...,324754402,NaN
1,1974262825943023975,Fri Oct 03 23:58:32 +0000 2025,0,#wts pc iu dom sby bs co via tokped/tiktok sho...,1974262825943023975,https://pbs.twimg.com/media/G2X9k1OaAAAg2EF.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197426282594302...,324754402,NaN
2,1974262593326809467,Fri Oct 03 23:57:36 +0000 2025,0,Wts pc iu dom sby bs co via tokped/tiktok shop...,1974262593326809467,https://pbs.twimg.com/media/G2X9XTVbMAErpdu.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197426259332680...,324754402,NaN
3,1974262238631665814,Fri Oct 03 23:56:12 +0000 2025,1,Wts pc iu dom sby bs co via tokped/tiktok shop...,1974262238631665814,https://pbs.twimg.com/media/G2X9CxfaIAAMy94.jpg,NaN,in,NaN,0,0,3,https://x.com/undefined/status/197426223863166...,324754402,NaN
4,1974256815903838591,Fri Oct 03 23:48:19 +0000 2025,2,@betterBenz Hahahaha...bisa jadi bang benz Aku...,1974260253219795329,NaN,betterBenz,in,NaN,0,1,0,https://x.com/undefined/status/197426025321979...,1603676136214777856,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1w8OgXk89PXoBuXS1vKraiPTJ4fTF6D-mcHHpODoNkiM/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-04.csv" -s "tiktok shop since:2025-10-04 until:2025-10-05 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-04 until:2025-10-05 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-04.csv
Total tweets saved: 19

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-04.csv
Total tweets saved: 35

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-04.csv
Total tweets saved: 39
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 39 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-04.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1974610471836881195,Sat Oct 04 22:59:57 +0000 2025,0,Tiktok shop got me again,1974610471836881195,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197461047183688...,1680767449883451394,NaN
1,1974608377528623566,Sat Oct 04 22:51:38 +0000 2025,0,YA QUR ME MANDEN MI PEDIDO DE TIKTOK SHOP,1974608377528623566,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197460837752862...,1008103521625858048,NaN
2,1974604192544358736,Sat Oct 04 22:35:00 +0000 2025,4,[Bisa beli lagi] Lumayan buat simpenan emas ju...,1974604192544358736,https://pbs.twimg.com/media/G2c0C-bboAADNkA.jpg,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197460419254435...,1305090402626617344,NaN
3,1974603170447032789,Sat Oct 04 22:31:15 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1974603246921818359,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197460324692181...,1198334086588186624,NaN
4,1974596733817790903,Sat Oct 04 22:05:22 +0000 2025,0,Coba lihat produk ini! https://t.co/lGwzS1nk4a,1974596733817790903,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197459673381779...,1470352494245023744,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1zG3yoYe3Yv9ZfP5RDI1AIiaiKG7ZNqd9oacOpa-5Ah4/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-05.csv" -s "tiktok shop since:2025-10-05 until:2025-10-06 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-05 until:2025-10-06 lang:id

 (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-05.csv
Total tweets saved: 18

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-05.csv
Total tweets saved: 27

-- Scrolling... (1) (2) (3)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 27 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-05.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1974806840060891304,Sun Oct 05 12:00:15 +0000 2025,0,pompa kuras pembersih air aquarium Untuk produ...,1974806840060891304,https://pbs.twimg.com/ext_tw_video_thumb/19748...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197480684006089...,859673588374282240,NaN
1,1974805144014651711,Sun Oct 05 11:53:31 +0000 2025,0,cermin mata hitam murah pakai nampak bergaya t...,1974805144014651711,https://pbs.twimg.com/amplify_video_thumb/1974...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197480514401465...,920520967,NaN
2,1974804848370438379,Sun Oct 05 11:52:20 +0000 2025,0,Jam tangan mewah elegant tapi 20ribuan? Beli d...,1974804848370438379,https://pbs.twimg.com/ext_tw_video_thumb/19748...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197480484837043...,495631121,NaN
3,1974788525431337028,Sun Oct 05 10:47:33 +0000 2025,1,Amanin paket pink Memancing Bandeng Jodoh Kuga...,1974788544335167687,NaN,ralenaworld,in,NaN,0,1,0,https://x.com/undefined/status/197478854433516...,1760569904959496192,NaN
4,1974780277638721855,Sun Oct 05 10:14:42 +0000 2025,0,Atasan crop top kekinian! Shopee https://t.co/...,1974780277638721855,https://pbs.twimg.com/ext_tw_video_thumb/19747...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197478027763872...,495631121,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/12JrlwKGduDMltkpW_ze2VNV_Co-rjuYLw8Y7I5DBtZc/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-06.csv" -s "tiktok shop since:2025-10-06 until:2025-10-07 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-06 until:2025-10-07 lang:id

 (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-06.csv
Total tweets saved: 16

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-06.csv
Total tweets saved: 24

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 24 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-06.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1975332153941782903,Mon Oct 06 22:47:40 +0000 2025,0,BUKU SELF IMPROVEMENT CEPAT &amp; MUDAH LANCAR...,1975332153941782903,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197533215394178...,2452389078,NaN
1,1975325196979761471,Mon Oct 06 22:20:01 +0000 2025,0,TikTok shop selling face adidas Jellyfish btw ...,1975325196979761471,https://pbs.twimg.com/media/G2nDy-1bIAQTfpV.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197532519697976...,575169872,NaN
2,1975314272453632182,Mon Oct 06 21:36:36 +0000 2025,0,Jam tangan korean style hanya 30ribuan Beli di...,1975314272453632182,https://pbs.twimg.com/ext_tw_video_thumb/19753...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197531427245363...,495631121,NaN
3,1975282848564498505,Mon Oct 06 19:31:44 +0000 2025,0,Any facebook ad tiktok ad tiktok shop media bu...,1975282848564498505,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197528284856449...,1762164967971717121,NaN
4,1975278263594590356,Mon Oct 06 19:13:31 +0000 2025,0,me rendi pro tiktok shop,1975278263594590356,NaN,NaN,tl,NaN,0,1,0,https://x.com/undefined/status/197527826359459...,1547116885250113537,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1acmb9WQX5qrrgDyzjFBlFA-jHFqgAqZB1wsWezOUpvc/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-07.csv" -s "tiktok shop since:2025-10-07 until:2025-10-08 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-07 until:2025-10-08 lang:id

 (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-07.csv
Total tweets saved: 18

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-07.csv
Total tweets saved: 38

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-07.csv
Total tweets saved: 55

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-07.csv
Total tweets saved: 72

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 72 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-07.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1975712432313291168,Tue Oct 07 23:58:45 +0000 2025,0,BUKU TKA BANK SOAL TKA SMP/MTS 2026 (Sesuai Pe...,1975712432313291168,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197571243231329...,2452389078,NaN
1,1975703665651618260,Tue Oct 07 23:23:55 +0000 2025,0,Lucunyaa mana murah bgt lagi Shopee : https://...,1975703665651618260,https://pbs.twimg.com/ext_tw_video_thumb/19757...,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197570366565161...,1334034831164936192,NaN
2,1975699846775681401,Tue Oct 07 23:08:44 +0000 2025,0,Beli NMAX juga lebih murah di TikTok Shop Coba...,1975699846775681401,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197569984677568...,118138830,NaN
3,1975699692962128145,Tue Oct 07 23:08:08 +0000 2025,0,Beli Alphard lebih murah di TikTok Shop loh Co...,1975699692962128145,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197569969296212...,118138830,NaN
4,1975649870095524024,Tue Oct 07 19:50:09 +0000 2025,0,Ok TikTok shop is legit. (IYKYK) https://t.co/...,1975649870095524024,https://pbs.twimg.com/media/G2rrFc2XwAAinia.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197564987009552...,2822211470,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1nFbff0tWNe2kRlTehTeGcbQDhhmxf7tYHq8TMHo_gkM/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-08.csv" -s "tiktok shop since:2025-10-08 until:2025-10-09 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-08 until:2025-10-09 lang:id

 (3) (4) (5) (6) (7)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-08.csv
Total tweets saved: 15

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-08.csv
Total tweets saved: 32

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 32 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-08.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1975908282834563233,Wed Oct 08 12:56:59 +0000 2025,2,Aku order 2 barang di hari yang sama 2 jasa ki...,1975908282834563233,NaN,NaN,in,NaN,0,2,0,https://x.com/undefined/status/197590828283456...,1704501246231449600,NaN
1,1975906717025325469,Wed Oct 08 12:50:46 +0000 2025,47,Buat kalian yang mau beli merch Kath inc sekar...,1975906717025325469,https://pbs.twimg.com/ext_tw_video_thumb/19759...,NaN,in,NaN,2,0,11,https://x.com/undefined/status/197590671702532...,1178943966063943680,NaN
2,1975729138158760158,Wed Oct 08 12:17:34 +0000 2025,0,@tanyakanrl buat liat² tiktok shop doang biasa...,1975898361447493883,NaN,tanyakanrl,in,NaN,0,0,0,https://x.com/undefined/status/197589836144749...,1199172783185391616,NaN
3,1975895958765596949,Wed Oct 08 12:08:59 +0000 2025,6,belinya di sini ↓ shopee: https://t.co/GF8ReT3...,1975896203641737287,NaN,_matchagalu,in,NaN,0,1,0,https://x.com/undefined/status/197589620364173...,1915302007050821637,NaN
4,1975895958765596949,Wed Oct 08 12:08:49 +0000 2025,5,belinya di sini ↓ shopee: https://t.co/Zqc6TDW...,1975896157932188023,NaN,_matchagalu,in,NaN,0,1,0,https://x.com/undefined/status/197589615793218...,1915302007050821637,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1-RsVKs-UD5nrzTsUj9G6xQdcgM-KZ9iz6Wr4Sc-kliI/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-09.csv" -s "tiktok shop since:2025-10-09 until:2025-10-10 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-09 until:2025-10-10 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-09.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-09.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-09.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-09.csv
Total tweets saved: 70

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 70 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-09.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1976401394518327434,Thu Oct 09 21:36:26 +0000 2025,2,look tiktok shop,1976401394518327434,NaN,NaN,sv,NaN,0,0,0,https://x.com/undefined/status/197640139451832...,1818296330365935616,NaN
1,1976396092133736860,Thu Oct 09 21:15:22 +0000 2025,0,pertama kali buka tiktok shop. seru juga yak.,1976396092133736860,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197639609213373...,759075099307749376,NaN
2,1976356320312951151,Thu Oct 09 18:37:20 +0000 2025,6,Diskon Toko 10rb &amp; 20rb Tanpa Minimal Pemb...,1976356320312951151,https://pbs.twimg.com/media/G21tmQaaAAA2ims.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197635632031295...,1305090402626617344,NaN
3,1976356222577279420,Thu Oct 09 18:36:57 +0000 2025,2,Serba 100 perak https://t.co/TP9BMYMw6E Morris...,1976356222577279420,https://pbs.twimg.com/media/G21tgKKbEAAv8T1.jpg,NaN,in,NaN,0,0,1,https://x.com/undefined/status/197635622257727...,2384473045,NaN
4,1976338079880556975,Thu Oct 09 17:24:51 +0000 2025,0,[NEW LAUNCH ALERT] Lip Tint lembab &amp; glos...,1976338079880556975,https://pbs.twimg.com/media/G21dAeNaAAAXdpY.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197633807988055...,1050338480834764800,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1hekCKlx_H1U25-_XhUVCtev5wden0_dY--sg2DTFLzI/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-10.csv" -s "tiktok shop since:2025-10-10 until:2025-10-11 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-10 until:2025-10-11 lang:id

 (3) (4) (5) (6) (7) (8) (9) (10) (11)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-10.csv
Total tweets saved: 20

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-10.csv
Total tweets saved: 39

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 39 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-10.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1976603696235745593,Fri Oct 10 11:00:19 +0000 2025,0,Jam tangan murah mewah! Beli disini Shopee htt...,1976603696235745593,https://pbs.twimg.com/ext_tw_video_thumb/19766...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197660369623574...,495631121,NaN
1,1976548324678455607,Fri Oct 10 10:57:03 +0000 2025,1,@sukaikangurame di tiktok shop 200k kemarin ak...,1976602872788963692,NaN,sukaikangurame,in,NaN,0,0,0,https://x.com/undefined/status/197660287278896...,1186269461755490304,NaN
2,1976602289894007278,Fri Oct 10 10:54:44 +0000 2025,38,Live eksklusif #OPPOA6Pro bareng Afdhal Yusman...,1976602289894007278,https://pbs.twimg.com/media/G25NTcbasAAn_HD.jpg,NaN,in,NaN,0,2,3,https://x.com/undefined/status/197660228989400...,1220746218,NaN
3,1976593023074181451,Fri Oct 10 10:51:45 +0000 2025,0,@kaelakovalskia ada shopee dan tokped juga loh...,1976601539893661851,NaN,kaelakovalskia,in,NaN,0,0,0,https://x.com/undefined/status/197660153989366...,1637826426178260992,NaN
4,1976593231493378448,Fri Oct 10 10:18:44 +0000 2025,0,mmg betul2 racun mainan kakak naga ni auto ras...,1976593231493378448,https://pbs.twimg.com/amplify_video_thumb/1976...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197659323149337...,920520967,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1BAGv_aEVGuXhvMeyeylgNcnZtQdibAjqMxgXZttPsSA/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-11.csv" -s "tiktok shop since:2025-10-11 until:2025-10-12 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3) (4)
Filling in keywords: tiktok shop since:2025-10-11 until:2025-10-12 lang:id

 (5)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-11.csv
Total tweets saved: 20

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-11.csv
Total tweets saved: 32
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 32 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-11.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1977152515469635745,Sat Oct 11 23:21:08 +0000 2025,0,AI Profit with TikTok Shop https://t.co/XSsTQD...,1977152515469635745,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197715251546963...,74794018,NaN
1,1977111936396558493,Sat Oct 11 20:42:51 +0000 2025,0,@sachitheworld Tiktok shop emang suka tiba² ad...,1977112682689184106,NaN,sachitheworld,in,NaN,0,0,0,https://x.com/undefined/status/197711268268918...,1665712564607811586,NaN
2,1977110308696343018,Sat Oct 11 20:33:25 +0000 2025,0,to sendo influenciada pelo tiktok shop ️️️️,1977110308696343018,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197711030869634...,1022252366907797504,NaN
3,1977061256415809556,Sat Oct 11 17:18:30 +0000 2025,0,Astaga mengcapek sama admin e-commerce sekaran...,1977061256415809556,https://pbs.twimg.com/media/G2_uvAXbEAAw1SF.jpg,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197706125641580...,1682929800653201408,NaN
4,1977018668291912050,Sat Oct 11 16:51:17 +0000 2025,2,Kedua ada Good/Bad Fortune yang masih bisa kam...,1977054407230734579,https://pbs.twimg.com/media/G2_ogXob0AA7vDr.jpg,id_akad,in,NaN,0,0,0,https://x.com/undefined/status/197705440723073...,1341650815157563392,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1MWXXqGl8kAzw5JuGuEwP-2vI_oYsElV_Us4aGileBOA/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-12.csv" -s "tiktok shop since:2025-10-12 until:2025-10-13 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-12 until:2025-10-13 lang:id

 (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-12.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-12.csv
Total tweets saved: 38

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 38 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-12.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1977513910522777741,Sun Oct 12 23:17:11 +0000 2025,0,huweee ada yang pernah belanja di tiktok shop ...,1977513910522777741,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197751391052277...,826997821,NaN
1,1977510592652120387,Sun Oct 12 23:04:00 +0000 2025,0,Buku Pintar Kuasai Excel Untuk Persiapan Kerja...,1977510592652120387,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197751059265212...,2452389078,NaN
2,1977500702151729580,Sun Oct 12 22:24:42 +0000 2025,0,Aconteceu Me rendi ao tiktok shop,1977500702151729580,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197750070215172...,98261425,NaN
3,1977450591699013842,Sun Oct 12 19:05:34 +0000 2025,0,Pengen makan tteokbeokki.. iklannya lewat mulu...,1977450591699013842,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197745059169901...,4858400124,NaN
4,1977446018993246354,Sun Oct 12 18:47:24 +0000 2025,0,sistem BCA kacau anjay Duit gua ilang 7 5jt gi...,1977446018993246354,NaN,NaN,in,NaN,0,5,0,https://x.com/undefined/status/197744601899324...,1295885178930307072,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/13ut3ZQCKIqkdApscbjoaB04jpf9oh435vGDrcP3fFQc/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-13.csv" -s "tiktok shop since:2025-10-13 until:2025-10-14 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-13 until:2025-10-14 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-13.csv
Total tweets saved: 19

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-13.csv
Total tweets saved: 26

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 26 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-13.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1977883678723194908,Mon Oct 13 23:46:30 +0000 2025,1,Masya Allah tabarakallah #berbagi #permentrela...,1977883678723194908,https://pbs.twimg.com/ext_tw_video_thumb/19778...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197788367872319...,1930988066577240064,NaN
1,1977877609821126992,Mon Oct 13 23:22:24 +0000 2025,0,Buku Psikologi - Trik Memikat &amp; Mempengaru...,1977877609821126992,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197787760982112...,2452389078,NaN
2,1977815763114467655,Mon Oct 13 19:25:40 +0000 2025,0,@kyotogpro @DEANDRY90 by psychological memang ...,1977818036632776724,NaN,kyotogpro,in,NaN,0,0,0,https://x.com/undefined/status/197781803663277...,1210585896904380416,NaN
3,1977795513031475365,Mon Oct 13 19:17:16 +0000 2025,1,@Kurogane_Endo tiktok shop kekw,1977815921592082676,NaN,Kurogane_Endo,in,NaN,0,1,0,https://x.com/undefined/status/197781592159208...,1267253724206059521,NaN
4,1977800046025257294,Mon Oct 13 18:14:41 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1977800172781318176,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197780017278131...,1198334086588186624,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1pg1xwm78VYrAhp-y1b9CkyEEOWCfEl3Yu8HQSs5X-1w/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-14.csv" -s "tiktok shop since:2025-10-14 until:2025-10-15 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-14 until:2025-10-15 lang:id

 (4) (5) (6) (7) (8) (9)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-14.csv
Total tweets saved: 19

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-14.csv
Total tweets saved: 36
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 36 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-14.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1978081481705619537,Tue Oct 14 12:52:30 +0000 2025,0,lampu taman solar cell ini dapat diubah bentuk...,1978081481705619537,https://pbs.twimg.com/ext_tw_video_thumb/19780...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197808148170561...,859673588374282240,NaN
1,1978076799897587862,Tue Oct 14 12:33:54 +0000 2025,0,Miniset Fema 1182 Ukuran: all size Harga: 25.0...,1978076799897587862,https://pbs.twimg.com/media/G3OKV7rbAAA6-tS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197807679989758...,1555538087010127872,NaN
2,1978075354645283041,Tue Oct 14 12:28:10 +0000 2025,0,Celana dalam highwaist Vi&amp;BB Ukuran: XL Ha...,1978075354645283041,https://pbs.twimg.com/media/G3OJBiQbwAARbn6.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197807535464528...,1555538087010127872,NaN
3,1978073204154319050,Tue Oct 14 12:19:37 +0000 2025,0,Miniset Fema 0282 Ukuran: all size Harga: 25.0...,1978073204154319050,https://pbs.twimg.com/media/G3OHEkwaQAAA83N.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197807320415431...,1555538087010127872,NaN
4,1978070006731506021,Tue Oct 14 12:06:55 +0000 2025,0,Boxer pria Uomo Ukuran: all size Harga: 20.000...,1978070006731506021,https://pbs.twimg.com/media/G3OEJ9fa8AAw4hj.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197807000673150...,1555538087010127872,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1zhAfN0Oc3h9o4mzkeGI_5iEyhXBkaDKndiDChPyyAgE/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-15.csv" -s "tiktok shop since:2025-10-15 until:2025-10-16 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-15 until:2025-10-16 lang:id



Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-15.csv
Total tweets saved: 20

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-15.csv
Total tweets saved: 40


Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-15.csv
Total tweets saved: 43
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 43 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-15.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1978599797146960181,Wed Oct 15 23:12:06 +0000 2025,0,Buku Psikologi - Trik Memikat &amp; Mempengaru...,1978599797146960181,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197859979714696...,2452389078,NaN
1,1978546935456821571,Wed Oct 15 23:11:03 +0000 2025,0,@ElusiveIno Beli dmn sih selain tiktok shop,1978599531701998006,NaN,ElusiveIno,in,NaN,0,1,0,https://x.com/undefined/status/197859953170199...,591518443,NaN
2,1978586951985795498,Wed Oct 15 22:21:43 +0000 2025,6,@jakebrodes jd vance s tiktok shop,1978587116176081239,NaN,jakebrodes,in,NaN,0,0,0,https://x.com/undefined/status/197858711617608...,2912618567,NaN
3,1978578700107960502,Wed Oct 15 21:48:16 +0000 2025,0,hi guys gue lagi mencoba belajar pake TikTok shop,1978578700107960502,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197857870010796...,1803808397164470274,NaN
4,1978571187413209461,Wed Oct 15 21:18:25 +0000 2025,0,Buku Putih Tiktok Affiliate https://t.co/dO9Jg...,1978571187413209461,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197857118741320...,1623554853883777025,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1ustx87novDWfwcgLMQbz_cTYdk1iqH-N-hatIBA0p1Y/edit#gid=0

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'YOUR_AUTH_TOKEN' # change this auth token

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-16.csv" -s "tiktok shop since:2025-10-16 until:2025-10-17 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-16 until:2025-10-17 lang:id

 (2) (3)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-16.csv
Total tweets saved: 18

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-16.csv
Total tweets saved: 38

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-16.csv
Total tweets saved: 51

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 51 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-16.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1978606672710181345,Thu Oct 16 22:20:55 +0000 2025,0,@Unclemage1 Bisa di tiktok shop atau shopee kak,1978949301595443401,NaN,Unclemage1,in,NaN,0,0,0,https://x.com/undefined/status/197894930159544...,1216570379390439424,NaN
1,1978871214581125269,Thu Oct 16 17:15:31 +0000 2025,1,@manifestopus TikTok shop strikes again,1978872447920398409,NaN,manifestopus,in,NaN,0,0,0,https://x.com/undefined/status/197887244792039...,1936516313083707392,NaN
2,1978879480325415284,Thu Oct 16 18:18:36 +0000 2025,0,@axyowk Kalo jnt cepet cuman ya gitu setauku k...,1978888323088130551,NaN,axyowk,in,NaN,0,0,0,https://x.com/undefined/status/197888832308813...,1328230783165743105,NaN
3,1978882155418681714,Thu Oct 16 17:54:33 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1978882270472626294,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197888227047262...,1198334086588186624,NaN
4,1978881211494772999,Thu Oct 16 17:51:14 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1978881434782716126,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/197888143478271...,1198334086588186624,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1-P40xBbpfwU8KEXBfjjW-kITQ9nAotGgeE7hYe4Xic0/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-17.csv" -s "tiktok shop since:2025-10-17 until:2025-10-18 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/tiktokshop_2025-10-17.csv, renaming to ./tweets-data/tiktokshop_2025-10-17.old.csv

-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-17 until:2025-10-18 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-17.csv
Total tweets saved: 18

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-17.csv
Total tweets saved: 38

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-17.csv
Total tweets saved: 58

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 58 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-17.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1979330878649307518,Fri Oct 17 23:37:10 +0000 2025,0,Buku Putih Tiktok Affiliate https://t.co/Luji0...,1979330878649307518,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197933087864930...,2488217768,NaN
1,1979328611648966797,Fri Oct 17 23:28:09 +0000 2025,1,Sayang kalian #amisiamuna #santri #Ngaji #vira...,1979328611648966797,https://pbs.twimg.com/ext_tw_video_thumb/19793...,NaN,tl,NaN,0,0,0,https://x.com/undefined/status/197932861164896...,1930988066577240064,NaN
2,1979324479848485208,Fri Oct 17 23:11:44 +0000 2025,1,Sayang Kalian #santri #loveyou #ngaji #amisiam...,1979324479848485208,https://pbs.twimg.com/ext_tw_video_thumb/19793...,NaN,tl,NaN,0,0,0,https://x.com/undefined/status/197932447984848...,1930988066577240064,NaN
3,1979321076560859542,Fri Oct 17 22:58:13 +0000 2025,0,Buku panduan komplet investasi saham : financi...,1979321076560859542,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197932107656085...,2452389078,NaN
4,1979279606894223841,Fri Oct 17 20:13:26 +0000 2025,0,tiktok shop chega mesmo galera️,1979279606894223841,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197927960689422...,842762647540056067,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1F4kBq0ms0EaL_2S1jaLkqL6q-hsoWa_YX8Elho-mYfo/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-18.csv" -s "tiktok shop since:2025-10-18 until:2025-10-19 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-18 until:2025-10-19 lang:id

 (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-18.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-18.csv
Total tweets saved: 32

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-18.csv
Total tweets saved: 38
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 38 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-18.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1979692954928480440,Sat Oct 18 23:35:56 +0000 2025,1,Serius deh cakep banget Khimar + gamisnyaaa Sh...,1979692954928480440,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197969295492848...,1930988066577240064,NaN
1,1979691606103236795,Sat Oct 18 23:30:34 +0000 2025,3,Racun shopee racun tiktok shop itu emang bener...,1979691606103236795,NaN,NaN,in,NaN,0,2,0,https://x.com/undefined/status/197969160610323...,1108534820311715840,NaN
2,1979605788592349270,Sat Oct 18 23:26:18 +0000 2025,0,@RandomBoyOnTwit bukaaaan beli di tiktok shop,1979690532147511635,NaN,RandomBoyOnTwit,in,NaN,0,0,0,https://x.com/undefined/status/197969053214751...,1162743141394292736,NaN
3,1979685469031194975,Sat Oct 18 23:06:11 +0000 2025,1,Sayang Kalian #fypシ #viral #amisiamuna #lucu #...,1979685469031194975,https://pbs.twimg.com/ext_tw_video_thumb/19796...,NaN,tl,NaN,0,0,0,https://x.com/undefined/status/197968546903119...,1930988066577240064,NaN
4,1979670363484348586,Sat Oct 18 22:27:39 +0000 2025,0,@yasbolv chega coisa do tiktok shop ???,1979675772295287300,NaN,yasbolv,in,NaN,0,0,0,https://x.com/undefined/status/197967577229528...,1611080798735589388,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1WppoqXRZ4yzGndbD9K67oStLtzwM6GNLPrgiE8JvFKQ/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-19.csv" -s "tiktok shop since:2025-10-19 until:2025-10-20 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-19 until:2025-10-20 lang:id

 (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-19.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-19.csv
Total tweets saved: 21

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 21 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-19.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1980046982803759454,Sun Oct 19 23:02:42 +0000 2025,1,Semangat terus yaa nak belajarnyaa #semangat #...,1980046982803759454,https://pbs.twimg.com/ext_tw_video_thumb/19800...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198004698280375...,1930988066577240064,NaN
1,1980028610305228893,Sun Oct 19 21:49:42 +0000 2025,0,Subuh2 scroll tiktok shop malah checkout maina...,1980028610305228893,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198002861030522...,86111232,NaN
2,1980003602027430218,Sun Oct 19 20:11:05 +0000 2025,1,@RealJonahBlake tiktok shop tuah,1980003790871838838,NaN,JonahBlake,in,NaN,0,0,0,https://x.com/undefined/status/198000379087183...,1896652381,NaN
3,1979982844467573020,Sun Oct 19 19:01:46 +0000 2025,0,@karsyn_bailee tiktok shop tuah,1979986350314025341,NaN,karsyn_bailee,in,NaN,0,0,0,https://x.com/undefined/status/197998635031402...,1896652381,NaN
4,1979979247075684480,Sun Oct 19 18:33:33 +0000 2025,0,levei golpe no tiktok shop vtmnc,1979979247075684480,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197997924707568...,1229068644866498560,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/11j624AudOAHcY1yJNAbGvbLbCEKO3vNyXjI4NgnXGyk/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-20.csv" -s "tiktok shop since:2025-10-20 until:2025-10-21 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-20 until:2025-10-21 lang:id

 (2) (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-20.csv
Total tweets saved: 20


Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-20.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-20.csv
Total tweets saved: 47

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 47 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-20.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1980419771675078792,Mon Oct 20 23:44:02 +0000 2025,1,Cek cek Shopee : https://t.co/ThMthE8qtL Tikto...,1980419771675078792,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198041977167507...,1930988066577240064,NaN
1,1980409144617365762,Mon Oct 20 23:01:48 +0000 2025,1,Semangat Kalian Pasti bisa #fyp #viral #santri...,1980409144617365762,https://pbs.twimg.com/ext_tw_video_thumb/19804...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198040914461736...,1930988066577240064,NaN
2,1980385193279300041,Mon Oct 20 21:26:38 +0000 2025,0,BUKU PUTIH TIKTOK AFFILIATE https://t.co/x1s4x...,1980385193279300041,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198038519327930...,1714194329680633857,NaN
3,1980370085161365776,Mon Oct 20 20:26:36 +0000 2025,2,sou ateu de tiktok shop e temu,1980370085161365776,NaN,NaN,in,NaN,1,0,2,https://x.com/undefined/status/198037008516136...,1583818396315095040,NaN
4,1980086416853073999,Mon Oct 20 19:02:33 +0000 2025,0,@anabzxx o tiktok shop ta um inferno,1980348935429582916,NaN,anabzxx,in,NaN,0,1,0,https://x.com/undefined/status/198034893542958...,1772671557963239424,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/15HSRFEoscwVDnzwgz2IE9IZaNdJu1uYRrK5BC1Soc80/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-21.csv" -s "tiktok shop since:2025-10-21 until:2025-10-22 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-21 until:2025-10-22 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-21.csv
Total tweets saved: 19

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-21.csv
Total tweets saved: 29
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 29 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-21.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1980754141325459587,Tue Oct 21 21:53:10 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1980754256425525582,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198075425642552...,1198334086588186624,NaN
1,1980753041314750910,Tue Oct 21 21:48:57 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1980753197024031159,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198075319702403...,1198334086588186624,NaN
2,1980752390656528586,Tue Oct 21 21:46:06 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1980752480007758082,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198075248000775...,1198334086588186624,NaN
3,1980744982987206779,Tue Oct 21 21:17:09 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1980745195416162614,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198074519541616...,1198334086588186624,NaN
4,1980450681699140093,Tue Oct 21 18:48:29 +0000 2025,0,@lssza TikTok shop IKKKKKKKK,1980707781066764306,NaN,lssza,in,NaN,0,1,0,https://x.com/undefined/status/198070778106676...,1770481678399479808,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1UPibiZ3b_HMBVraiAjurS7LNtJxPby9xBnXptV-xPVY/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-22.csv" -s "tiktok shop since:2025-10-22 until:2025-10-23 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-22 until:2025-10-23 lang:id

 (4) (5) (6) (7)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-22.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-22.csv
Total tweets saved: 33

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 33 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-22.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1981000807437979660,Wed Oct 22 14:13:17 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1981000911083442493,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198100091108344...,1198334086588186624,NaN
1,1981000711799439518,Wed Oct 22 14:12:29 +0000 2025,0,Pengukus Periuk Nonstick Queenn Rumah Tangga 3...,1981000711799439518,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198100071179943...,848114775309471744,NaN
2,1980997468985979203,Wed Oct 22 13:59:36 +0000 2025,0,Sepatu flat slip on model terbaru nih beli dis...,1980997468985979203,https://pbs.twimg.com/ext_tw_video_thumb/19809...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198099746898597...,495631121,NaN
3,1980993058587255202,Wed Oct 22 13:42:08 +0000 2025,2,Jangan sampai ketinggalan yaaa Shopee Mall Ter...,1980993071644078562,https://pbs.twimg.com/media/G33msioXwAAeiwJ.jpg,teratubeauty,in,NaN,1,0,0,https://x.com/undefined/status/198099307164407...,1497254002349654018,NaN
4,1980987408134164719,Wed Oct 22 13:21:42 +0000 2025,0,tapi karena hobi buka tiktok shop dan shopee t...,1980987931394535750,NaN,virgology_,in,NaN,0,0,0,https://x.com/undefined/status/198098793139453...,1084652336545378304,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1kQWPjhlCDIYvCqQsao7j4pExGfGcZWKrXyXSgwUpct8/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-23.csv" -s "tiktok shop since:2025-10-23 until:2025-10-24 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-23 until:2025-10-24 lang:id

 (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-23.csv
Total tweets saved: 19

-- Scrolling... (1) (2) (3)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 19 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-23.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1981504235608166525,Thu Oct 23 23:47:05 +0000 2025,0,Sejarah Gerakan Kemerdekaan Palestina #HAMAS -...,1981507700195545110,NaN,arsipinfo,in,NaN,1,0,0,https://x.com/undefined/status/198150770019554...,938631266,NaN
1,1981493851560038422,Thu Oct 23 22:52:03 +0000 2025,0,Buku KUHP &amp; KUHAP : Berdasarkan UU RI No. ...,1981493851560038422,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198149385156003...,2452389078,NaN
2,1981450788607250820,Thu Oct 23 20:00:56 +0000 2025,0,Dimulai dari keresahan banyak banget klien-kli...,1981450788607250820,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198145078860725...,3271620138,NaN
3,1981410936121675943,Thu Oct 23 17:23:27 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1981411159711289392,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198141115971128...,1198334086588186624,NaN
4,1981390147561410649,Thu Oct 23 17:23:27 +0000 2025,0,@wonventeen dia ada tiktok shop tapi handle po...,1981411156607848613,NaN,wonventeen,in,NaN,0,1,0,https://x.com/undefined/status/198141115660784...,982522237054943232,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1govATmw0CkeG3kQGKp5l6OSOOiOaeieIoCFRxs-V9k8/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-24.csv" -s "tiktok shop since:2025-10-24 until:2025-10-25 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3) (4)
Filling in keywords: tiktok shop since:2025-10-24 until:2025-10-25 lang:id

 (5) (6)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-24.csv
Total tweets saved: 12

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 12 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-24.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1981864684031766623,Fri Oct 24 23:25:36 +0000 2025,27,Pake ini murah di tiktok shop. Ga usah sombong...,1981864684031766623,https://pbs.twimg.com/media/G4D_alpXMAA9QxZ.jpg,NaN,in,NaN,2,4,7,https://x.com/undefined/status/198186468403176...,1592183802658377729,NaN
1,1981813970412671004,Fri Oct 24 20:04:34 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1981814093251301430,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198181409325130...,1198334086588186624,NaN
2,1981804942097621270,Fri Oct 24 19:28:57 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1981805127171551735,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198180512717155...,1198334086588186624,NaN
3,1981801414373327072,Fri Oct 24 19:14:42 +0000 2025,0,Shop at https://t.co/aXP4u0L2lC TikTok Shop: h...,1981801542723547254,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198180154272354...,1198334086588186624,NaN
4,1981801477875413175,Fri Oct 24 19:14:27 +0000 2025,4,begadang ngabisin duit alias co shopee tokped ...,1981801477875413175,https://pbs.twimg.com/media/G4DF8PmXEAAPUOX.jpg,NaN,in,NaN,1,1,0,https://x.com/undefined/status/198180147787541...,741759884929073152,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1nrbUlImkcDRfSQnbKsrcxG578xxJBQG_Q9B0Dg0qqYU/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-25.csv" -s "tiktok shop since:2025-10-25 until:2025-10-26 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3) (4)
Filling in keywords: tiktok shop since:2025-10-25 until:2025-10-26 lang:id

 (5)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-25.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-25.csv
Total tweets saved: 38

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-25.csv
Total tweets saved: 58

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 58 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-25.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1982229982400184722,Sat Oct 25 23:37:10 +0000 2025,0,Buku KUHP &amp; KUHAP : Berdasarkan UU RI No. ...,1982229982400184722,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198222998240018...,2452389078,NaN
1,1982223801766060331,Sat Oct 25 23:12:36 +0000 2025,0,Atasan oversize murah tapi kualitas ga kaleng2...,1982223801766060331,https://pbs.twimg.com/ext_tw_video_thumb/19822...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198222380176606...,495631121,NaN
2,1982219116820738505,Sat Oct 25 22:53:59 +0000 2025,0,Ecentio Mini Chopper Blender 6 pisau 250ml Por...,1982219116820738505,https://pbs.twimg.com/ext_tw_video_thumb/19822...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198221911682073...,153623736,NaN
3,1982194654494728498,Sat Oct 25 21:17:14 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1982194767464178035,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198219476746417...,1198334086588186624,NaN
4,1982194188994154996,Sat Oct 25 21:15:24 +0000 2025,0,Shop at https://t.co/aXP4u0Kuw4 TikTok Shop: h...,1982194306782748912,NaN,tionneskin,sv,NaN,0,0,0,https://x.com/undefined/status/198219430678274...,1198334086588186624,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1qSMs25k05ehEzMqJaHrNlCH6TiY1dOGxQ_yAc_MPT7Y/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-26.csv" -s "tiktok shop since:2025-10-26 until:2025-10-27 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tiktok shop since:2025-10-26 until:2025-10-27 lang:id

 (3) (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-26.csv
Total tweets saved: 8


Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-26.csv
Total tweets saved: 18

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-26.csv
Total tweets saved: 25
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 25 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-26.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1982120387568861487,Sun Oct 26 09:36:35 +0000 2025,1,@MikaelDewabrata sistem monetisasi? tiktok sho...,1982380830187192565,NaN,MikaelDewabrata,in,NaN,0,1,0,https://x.com/undefined/status/198238083018719...,933490676385189888,NaN
1,1982361235212681717,Sun Oct 26 08:18:43 +0000 2025,0,guyss mau nanya yang pernah refund barang di t...,1982361235212681717,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198236123521268...,1810109316789354497,NaN
2,1982357878393749947,Sun Oct 26 08:05:23 +0000 2025,0,sepanjang empat hari aku kat kampung. hari2 ad...,1982357878393749947,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198235787839374...,1313296758512869376,NaN
3,1982357577204969527,Sun Oct 26 08:04:11 +0000 2025,6,DANA Traktiran Gajian datang lagi Belanja di T...,1982357577204969527,https://pbs.twimg.com/media/G4K_tQTXAAAaOGL.jpg,NaN,in,NaN,0,0,2,https://x.com/undefined/status/198235757720496...,614421259,NaN
4,1982352219937890442,Sun Oct 26 07:42:54 +0000 2025,0,damn aku tak nak scroll tiktok shop lagi kan d...,1982352219937890442,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198235221993789...,1110427395121508353,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1SD-RjWScYAR9Z3H24JT67o0hRU4eKjwBsT17oSqU6ro/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-27.csv" -s "tiktok shop since:2025-10-27 until:2025-10-28 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-27 until:2025-10-28 lang:id

 (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-27.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-27.csv
Total tweets saved: 39

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 39 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-27.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1982950419576815782,Mon Oct 27 23:19:56 +0000 2025,1,tmnc meu oculos top chegou no tiktok shop agr ...,1982950419576815782,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198295041957681...,1597600236955893761,NaN
1,1982457216549425363,Mon Oct 27 22:33:02 +0000 2025,0,@heavyownn @tanyarlfes Beli di tiktok shop yg ...,1982938619645178035,NaN,heavyownn,in,NaN,0,0,0,https://x.com/undefined/status/198293861964517...,1196388960,NaN
2,1982922784390164826,Mon Oct 27 21:30:07 +0000 2025,0,Kaos cotton combed 24s dengan motif bunga bung...,1982922784390164826,https://pbs.twimg.com/ext_tw_video_thumb/19829...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198292278439016...,495631121,NaN
3,1982904902058946710,Mon Oct 27 20:19:03 +0000 2025,0,tiktok shop funciona mesmo bbd,1982904902058946710,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/198290490205894...,958097659172147200,NaN
4,1982891193739686082,Mon Oct 27 19:24:35 +0000 2025,2,anjir gaada yang kasih gua warning kalau jajan...,1982891193739686082,NaN,NaN,in,NaN,0,2,0,https://x.com/undefined/status/198289119373968...,1871874901008846849,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/13wnejq08Sn8OPdyipwiBRqtXLZS2hf2QI66y1eT5Fi0/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-28.csv" -s "tiktok shop since:2025-10-28 until:2025-10-29 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: tiktok shop since:2025-10-28 until:2025-10-29 lang:id

 (4)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-28.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-28.csv
Total tweets saved: 37

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-28.csv
Total tweets saved: 41
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 41 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-28.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1983270821335625861,Tue Oct 28 20:33:05 +0000 2025,1,03. Kipas Genggam Mini ultra (Klik link di baw...,1983270821335625861,https://pbs.twimg.com/media/G4X-TQtaUAEf5XN.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198327082133562...,1313376978133688322,NaN
1,1982997945164140635,Tue Oct 28 18:14:19 +0000 2025,0,@LyshaMauricex3 Nah man. In the tiktok shop??,1983235899329552655,NaN,LyshaMauricex3,in,NaN,0,0,0,https://x.com/undefined/status/198323589932955...,3313771604,NaN
2,1983225244945912112,Tue Oct 28 17:31:59 +0000 2025,5,Ngl fuck TikTok shop,1983225244945912112,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198322524494591...,1655427237317955590,NaN
3,1983211151442825218,Tue Oct 28 16:50:13 +0000 2025,0,@luvvminkoo Via tiktok shop nya langsung ka ta...,1983214735043555762,NaN,luvvminkoo,in,NaN,0,0,0,https://x.com/undefined/status/198321473504355...,1076903452435931136,NaN
4,1983206982208127156,Tue Oct 28 16:19:25 +0000 2025,1,my current fyp: coba melempar manggis sehat ta...,1983206982208127156,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198320698220812...,1239505233685778432,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1bCJLBE0zNaT90LG5jTj-bXTLQVKGeQ5ZueLEA0YMQg4/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-29.csv" -s "tiktok shop since:2025-10-29 until:2025-10-30 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: tiktok shop since:2025-10-29 until:2025-10-30 lang:id

 (2)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-29.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-29.csv
Total tweets saved: 39

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-29.csv
Total tweets saved: 51

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 51 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-29.csv')

# Tampilkan beberapa baris pertama
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1983677719809499569,Wed Oct 29 23:29:58 +0000 2025,0,[ 30 Oktober 2025 ] slamat pagiyy sayankOoO y...,1983677719809499569,https://pbs.twimg.com/media/G4dwX63a8AE9oqG.jpg,NaN,in,NaN,3,0,0,https://x.com/undefined/status/198367771980949...,733204059738509312,NaN
1,1983676206638842016,Wed Oct 29 23:23:57 +0000 2025,0,malam ngelive pagi di airport... Alhamdulillah...,1983676206638842016,https://pbs.twimg.com/media/G4du_0YasAApGLj.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198367620663884...,1963885886183280640,NaN
2,1983670104987725852,Wed Oct 29 22:59:42 +0000 2025,0,(AppelHouse x tiktok)iPhone 13 128GB New Garan...,1983670104987725852,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198367010498772...,834273341678579712,NaN
3,1983666309763338548,Wed Oct 29 22:44:37 +0000 2025,0,Buku Diet Intermittent Fasting: Langsing Tanpa...,1983666309763338548,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198366630976333...,2452389078,NaN
4,1983662440924770721,Wed Oct 29 22:29:15 +0000 2025,0,Syl kek lg live di tiktok shop,1983662440924770721,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/198366244092477...,1858725624409714691,NaN

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1deFSOGwp6tJqu1BBR3oF5pQ1kNMx0hz-qSZ0bp6hxoU/edit#gid=0

In [ ]:
!npx -y tweet-harvest@2.6.1 -o "tiktokshop_2025-10-31.csv" -s "tiktok shop since:2025-10-30 until:2025-11-31 lang:id" --tab "LATEST" -l 500 --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3) (4)
Filling in keywords: tiktok shop since:2025-10-30 until:2025-11-31 lang:id

 (5)

Your tweets saved to: /content/tweets-data/tiktokshop_2025-10-31.csv
Total tweets saved: 0

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)No tweets found for the search criteria
⠙

In [ ]:
import pandas as pd

# Baca file yang benar (sesuai hasil crawl)
df = pd.read_csv('tweets-data/tiktokshop_2025-10-30.csv')

# Tampilkan beberapa baris pertama
df.head()

EmptyDataError: No columns to parse from file

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1wWoUXg2SQC65DkhoHnh5H-Ga4y11gqaXbs3BO3NNEnE/edit#gid=0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import glob
import os

# GANTI path di bawah ini jika perlu.
# Path yang Anda berikan sebelumnya: '/content/drive/MyDrive/SNA/CSV/'
path_folder_xlsx = '/content/drive/MyDrive/SEM 5/SNA/bu novy/'

# Membuat pola untuk menemukan semua file yang berakhiran .xlsx
pola_file = os.path.join(path_folder_xlsx, "*.xlsx")

# Mengambil daftar semua nama file xlsx
semua_file_xlsx = glob.glob(pola_file)

# Memeriksa apakah file ditemukan
if not semua_file_xlsx:
    print(f"Error: Tidak ada file .xlsx yang ditemukan di folder '{path_folder_xlsx}'")
    print("Mohon periksa kembali path folder dan pastikan ekstensinya sudah benar .xlsx")
else:
    # Membaca setiap file xlsx dan menyimpannya dalam sebuah list
    list_df = []
    print(f"Menemukan {len(semua_file_xlsx)} file. Memulai proses penggabungan...")
    for file in semua_file_xlsx:
        try:
            # Menggunakan pd.read_excel untuk file .xlsx
            df_temp = pd.read_excel(file)
            list_df.append(df_temp)
            print(f"-> Berhasil membaca {os.path.basename(file)}")
        except Exception as e:
            print(f"Gagal membaca file {file}: {e}")

    # Menggabungkan semua dataframe dalam list menjadi satu dataframe tunggal
    if list_df:
        df_gabungan = pd.concat(list_df, ignore_index=True)

        # Menampilkan informasi ringkas tentang dataframe gabungan
        print("\n================ INFORMASI DATAFRAME GABUNGAN ================")
        print(f"Berhasil menggabungkan {len(semua_file_xlsx)} file XLSX.")
        print(df_gabungan.info())

        # Menampilkan 5 baris pertama dari dataframe gabungan
        print("\n================ 5 BARIS PERTAMA DATA ================")
        print(df_gabungan.head())
    else:
        print("Tidak ada data untuk digabungkan.")

Menemukan 30 file. Memulai proses penggabungan...
-> Berhasil membaca InteractiveSheet_2025-11-04_14_47_03.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_36_05.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_14_51.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_41_49.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_15_10.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_15_58_39.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_45_17.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_38_45.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_13_54_43.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_15_50_08.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_53_21.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_24_17.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_27_47.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_07_44.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_35_39.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_11_53.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_32_41.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_29_07.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_05_03.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_08_58.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_42_03.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_15_13.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_48_56.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_21_07.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_03_53.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_10_43.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_23_10.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-05_16_01_51.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_14_27_46.xlsx
-> Berhasil membaca InteractiveSheet_2025-11-04_15_32_34.xlsx

================ INFORMASI DATAFRAME GABUNGAN ================
Berhasil menggabungkan 30 file XLSX.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1281 entries, 0 to 1280
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1281 non-null   int64
 1   created_at               1281 non-null   object
 2   favorite_count           1281 non-null   int64
 3   full_text                1281 non-null   object
 4   id_str                   1281 non-null   int64
 5   image_url                462 non-null    object
 6   in_reply_to_screen_name  451 non-null    object
 7   lang                     1281 non-null   object
 8   location                 0 non-null      float64
 9   quote_count              1281 non-null   int64
 10  reply_count              1281 non-null   int64
 11  retweet_count            1281 non-null   int64
 12  tweet_url                1281 non-null   object
 13  user_id_str              1281 non-null   int64
 14  username                 0 non-null      float64
dtypes: float64(2), int64(7), object(6)
memory usage: 150.2+ KB
None

================ 5 BARIS PERTAMA DATA ================
   conversation_id_str                      created_at  favorite_count  \
0  1975712432313291264  Tue Oct 07 23:58:45 +0000 2025               0
1  1975703665651618304  Tue Oct 07 23:23:55 +0000 2025               0
2  1975699846775681280  Tue Oct 07 23:08:44 +0000 2025               0
3  1975699692962128128  Tue Oct 07 23:08:08 +0000 2025               0
4  1975649870095524096  Tue Oct 07 19:50:09 +0000 2025               0

                                           full_text               id_str  \
0  BUKU TKA BANK SOAL TKA SMP/MTS 2026 (Sesuai Pe...  1975712432313291264
1  Lucunyaa mana murah bgt lagi Shopee : https://...  1975703665651618304
2  Beli NMAX juga lebih murah di TikTok Shop Coba...  1975699846775681280
3  Beli Alphard lebih murah di TikTok Shop loh Co...  1975699692962128128
4  Ok TikTok shop is legit. (IYKYK) https://t.co/...  1975649870095524096

                                           image_url in_reply_to_screen_name  \
0                                                NaN                     NaN
1  https://pbs.twimg.com/ext_tw_video_thumb/19757...                     NaN
2                                                NaN                     NaN
3                                                NaN                     NaN
4    https://pbs.twimg.com/media/G2rrFc2XwAAinia.jpg                     NaN

  lang  location  quote_count  reply_count  retweet_count  \
0   in       NaN            0            0              0
1   in       NaN            0            1              0
2   in       NaN            0            0              0
3   in       NaN            0            0              0
4   in       NaN            0            0              0

                                           tweet_url          user_id_str  \
0  https://x.com/undefined/status/197571243231329...           2452389078
1  https://x.com/undefined/status/197570366565161...  1334034831164936192
2  https://x.com/undefined/status/197569984677568...            118138830
3  https://x.com/undefined/status/197569969296212...            118138830
4  https://x.com/undefined/status/197564987009552...           2822211470

   username
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

In [ ]:
# --- Tambahkan kode ini di akhir skrip Anda ---

# 1. Tentukan path LENGKAP di Google Drive untuk menyimpan file hasil
# Pastikan path ini benar dan Anda memiliki izin tulis
path_hasil_drive = '/content/drive/MyDrive/SEM 5/SNA/bu novy/HASIL_GABUNGAN.xlsx'

# 2. Simpan dataframe gabungan ke file Excel
# index=False agar nomor baris (indeks) pandas tidak ikut disimpan
print(f"\nMenyimpan hasil gabungan ke Google Drive di: {path_hasil_drive}...")
df_gabungan.to_excel(path_hasil_drive, index=False)

print("File berhasil disimpan ke Google Drive Anda.")

Menyimpan hasil gabungan ke Google Drive di: /content/drive/MyDrive/SEM 5/SNA/bu novy/HASIL_GABUNGAN.xlsx...
File berhasil disimpan ke Google Drive Anda.